### ISSUE TITLE
cannt install node cc package

### ISSUE THREAD

**Issue by mtiger2k** [postfinance/hlfabric-k8scc#6]
I tried demo, but failed to install node cc package.
Does it support node cc?

**Comment by djboris9** [comment]
Hi @mtiger2k 

Node should be supported as `hlfabric-k8scc` calls the HyperLedger code to get the build params and so on.
But at the time, it is only tested/used with Go.

Can you provide more information, what failed? (peer logs and some information about the enviroment/deployment)
Did you try some publicly available chaincode, so I can try to reproduce the error?

@mirioeggmann did you use it with node?

**Comment by mtiger2k** [comment]
thanks for your reply.

I used public marbles02 javascript cc.

firstly, I run your fabcar.tar.gz and it succeed.
then I copy marbles02 to pod, and package it.
`
kubectl cp chaincodes/marbles02 $(kubectl get pod -l app=cli.peer0.org1.example.com -o jsonpath="{.items[0].metadata.name}"):/chaincodes
peer lifecycle chaincode package marbles.tar.gz --path /chaincodes/marbles02/javascript/ --lang node --label marbles
`
then install it.
`
peer lifecycle chaincode install marbles.tar.gz
`

run kubectl describe pod xxx to see
 Warning  Failed     61s (x3 over 3m11s)  kubelet, docker-desktop  Failed to pull image "hyperledger/fabric-nodeenv:2.0.1": rpc error: code = Unknown desc = Error response from daemon: manifest for hyperledger/fabric-nodeenv:2.0.1 not found: manifest unknown: manifest unknown

And I checked docker hub, there is no 2.0.1 nodeenv.

So maybe you need to change nodeenv to latest 2.1.0, and rebuild it.

**Comment by djboris9** [comment]
Yes, you are right, this is definitely an issue. I will update the image versions on master soon

**Comment by djboris9** [comment]
Is it possible for you to try the new/latest version from master of `postfinance/hlfabric-k8scc`?


```
djurdjevicb@example.com # docker run --rm -ti postfinance/hlfabric-k8scc:latest@sha256:ab31ad659f23597c5f002bf3e69d249cb7e6b45fd76374a449042f8397102cb1 cat /opt/k8scc/k8scc.yaml
/etc/hyperledger/fabric/core.yaml: OK
patching file /etc/hyperledger/fabric/core.yaml
Running: cat /opt/k8scc/k8scc.yaml
---
images:
  golang: "hyperledger/fabric-ccenv:2.1.0"
  java: "hyperledger/fabric-javaenv:2.1.0"
  node: "hyperledger/fabric-nodeenv:2.1.0"
transfer_volume:
  path: "/var/lib/k8scc/transfer/"
  claim: "k8scc-transfer-pv"
builder:
  resources:
    memory_limit: "1G"
    cpu_limit: "0.5"
launcher:
  resources:
    memory_limit: "1G"
    cpu_limit: "0.5"
djurdjevicb@example.com #
```
