### ISSUE TITLE
Use builder image versions according to peer version

### ISSUE THREAD

**Issue by djboris9** [postfinance/hlfabric-k8scc#7]
## Issue
Solves image version problems like #6

## Proposal
Instead of hard coding builder image versions in `k8scc.yaml`, we should use the same substitution mechanism as in `core.yaml` to set the image version according to the peer version.

Example from `core.yaml`:
```
$(DOCKER_NS)/fabric-ccenv:$(TWO_DIGIT_VERSION)
```

## Implementation hint
Something like [this](https://github.com/hyperledger/fabric/blob/a362c28f59c925820973379696f29736bae13724/core/chaincode/platforms/util/utils.go#L172), but at runtime. We may need to start the peer binary in order to get the version. And maybe we can also process the `core.yaml` and remove the image versions from the `k8scc.yaml`.

**Comment by aldredb** [comment]
Hi @djboris9 a simpler alternative would be removing hardcoded `k8scc.yaml` from the image and relying on user-provided `ConfigMap` e.g.

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: org1-peer1-k8scc
data:
  k8scc.yaml: |
    ---
    images:
      golang: "hyperledger/fabric-ccenv:2.1.1"
      java: "hyperledger/fabric-javaenv:2.1.1"
      node: "hyperledger/fabric-nodeenv:2.1.1"
    transfer_volume:
      path: "/var/lib/k8scc/transfer/"
      claim: "shared-pvc"
    builder:
      resources:
        memory_limit: "500M"
        cpu_limit: "0.5"
    launcher:
      resources:
        memory_limit: "200M"
        cpu_limit: "0.1"
```
